name: "Craft Mining 6"
list:
  header: "----- Craft Mining -----"
  footer: "----- Season 6 -----"
levelingSystem:
  use: true
  rewards: true
  announce:
    legendary: true
    epic: true
    rare: false
    uncommon: false
    common: false
thunderSpawn:
  use: true
colors:
  accent1: 0x7704a8
  accent2: 0x0F01BC
spit:
  use: true
discord:
  use: false
  link: ""
teamspeak:
  use: false
  ip: ""
  isPasswordProtected: false
  password: ""
durabilityPing:
  use: true
  threshold: 0.1
mobHealthbar:
  use: true