levelingSystem:
  use: true
  rewards: true
  announce:
    legendary: true
    epic: true
    rare: false
    uncommon: false
    common: false
  categories:
    adventure: true
    building: true
    combat: true
    farming: true
    magic: true
    mining: true
    trading: true