# The main configuration file for the plugin.

# Important Stuff:

# Your SMP-Server Name:
name: "Craft Mining 6"

# The Header and Footer at the tab menu:
list:
  header: "----- Craft Mining -----"
  footer: "----- Season 6 -----"

# What are your primary and secondary colors?
# Use HEX-Colors for this.
# Formatting: "0x" + HEX-Color WITHOUT "#"!
colors:
  accent1: 0x7704a8
  accent2: 0x0F01BC

# Spawn: The Spawn is regulated in a different file. Use command to set the spawn.
spawn:
  # Can Player always tp to spawn with the command?
  commandTp: false

# Chat: Controlling the chat
chat:
  # Should the chat be disabled? Can also be toggled in-game (/chat <on/off>)
  disabled: false
  # Should there be a cooldown for the chat? (in seconds)
  # Set to 0 to disable.
  cooldown: 0

# Dimension: Lock and unlock the nether and the end.
# Either here or in-game through the command /dimension.
dimension:
  nether: false
  end: false


# Functions: These are functions, that can be turned on or off, either here or in-game through the command /functions.

# AFK: Use the AFK-System.
afk:
  # timeout: The time in minutes, after which a player is considered AFK.
  timeout: 5

# Teams:
teams:
  # Should the teams only be in colors of Minecraft, or can they also be custom (hex) colors?
  onlyMcColors: false
  # Can multiple Teams have the same color?
  sameColorMultipleTeams: false

# Leveling System
levelingSystem:
  use: true
  # Should rewards be given for leveling up?
  rewards: true
  # What rarity should or should not be announced in chat?
  announce:
    legendary: true
    epic: true
    rare: false
    uncommon: false
    common: false

# TPA: Teleport to a player.
tpaSystem:
  use: true

# Home: Set and teleport to a home.
homeSystem:
  use: true
  # How many homes can a player have?
  maxHomes: 5
  # Can the players in the team share one of their homes with the team?
  teamHomes: true

# Slime Chunk Check System: This function allows you to check if you are in a slime chunk.
# onlyCenter: Check only the chunk the player is standing in or also the nearby chunks (3x3)?
# save: Should the found chunks be saved for the player to look up later?
# checks: How many times can the player check for slime chunks?
# noneFoundNoRemove: Should the player get one check removed, if no slime chunks are found?
slimeChunkCheck:
  use: true
  onlyCenter: true
  save: true
  checks: 3
  noneFoundNoRemove: true

# Thunder Summoner:
# This function allows you to summon thunderstorms with throwing a trident at the highest block with the channeling enchantment.
# Uses 60% of the trident's durability.
thunderSpawn:
  use: true

# Durability Ping: Players get a ping, when their tool is about to break.
durabilityPing:
  use: true
  # The threshold is the percentage of durability, when the player gets a ping.
  threshold: 0.1

# Mob Healthbar: Players get a Healthbar at the actionbar, when they hit a mob.
mobHealthbar:
  use: true


# Misc Commands:

# Discord: This command gives you the link to the discord server.
discord:
  use: false
  link: ""

# Teamspeak: This command gives you the data to the teamspeak server.
teamspeak:
  use: false
  ip: ""
  isPasswordProtected: false
  password: ""

# Spit: This command allows you to spit on other players.
spit:
  use: true
